{% set name = "future_fstrings" %}
{% set version = "1.0.0" %}
{% set hash = "28a926ad769e1ff7f887bc4135921c42f4da570eab6d5e34cb366663e3182adf" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - tokenize-rt

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/asottile/future-fstrings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary:
    Adds fstrings for python<3.6

  description: |
    A backport of fstrings to python<3.6.
extra:
  recipe-maintainers:
    - sterlingbaldwin
    - deadsnakes-issues-bot
