appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 5Z1OJ9RSwtjClKERwYAUPwaW3k0FUIUdFdRz13jsctcU0hmhaTGCi539YuGo/3yh6smLKAnrcvcNCL3q49EETSfvzC9Eo5Bx971qobQatDKcs1D0GF3hW5wpB/OfPrUw6inSdW2urlRFTzUzoyc406uJA5VDAtXraMy47OgFLL9URZC9mV/4ORja6xf47Wf0GSBDj+ELqU4OOGm6Op1Ft9C+j5HOCHSLumN7X++MQ4XPqOYwAwgJ50nteleT1xcHMVrCIMQNNeGS0fTOfOaXgnJMmcRoh/9a6QPrKDHGZQmEpT+sb7eH2FDd4+vyIUB5Hmh+Of7UHRs8AJUsOSoGFhBNBk7ceGMFhRk4WR6tPO65LnS/o/cGWedAzrMTcg4yFQhbFux1+pTktzI3SmLSL01pOWzKQCflUsPKsrkPPVPJgMfNBxmtXhrZ4i/hTWvP99hS0cJhzSpuC+Cgaq1roeM01rGQsaRE3eQOlrI+S7V7ejYKH22RHkLOX/2Mzf6kOVbzEZSW/jGr/jj6dBF6wo6u98+aPQg0xaqcvqLawd68H8WT3oRKQBBsdoKhj0d/1sIUt085lEavWpMjBM9d+KCL+2IkH3EeYDrBkD2SPbCEIuQVd8XEOkA0yyy424Bn7y0DUdV5w4nPuvimmUICiGDEChhznvRcb918+7mkSfo=}
provider:
  win: azure
